---
title: "MSD 2019 Final Project"
author: "Sameer Jain (sj2736), Bailey Pearson (bp2471), Tanmay Chopra (tc2897)"
date: "`r Sys.time()`"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '3'
  pdf_document:
    toc: yes
    toc_depth: 3
subtitle: 'A replication and extension of  Predicting Positive and Negative Links
  in Online Social Networks by Jure Leskovec, Daniel Huttenlocher, and Jone Kleinberg,
  WWW 2010: ACM WWW International conference on World Wide Web, 2010'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(scales)
library(igraph)
library(tidyverse)
library(dplyr)
library(glmnet)

theme_set(theme_bw())
knitr::opts_chunk$set(echo = TRUE)
```

```{r read-data}
```

```{r logistic-regression}
epinions_edges <- read.delim("data/epinions.txt",col.names = c("FromNodeID","ToNodeID","Sign"))
epinion_nodes <- read.csv("nodes_features_epinions.csv", skip = 1)
epinions_embed <- read.csv("edges_features_epinions.csv")
temp_edges <- left_join(epinions_edges, epinions_embed, by = c("FromNodeID" = "u", "ToNodeID" = "v"))
in_features <- select(epinion_nodes,"node_id","total_in","pos_in","neg_in")
out_features <- select(epinion_nodes,"node_id","total_out","pos_out","neg_out")
master <- left_join(temp_edges, in_features, by = c("FromNodeID" = "node_id"))
master <- left_join(master, out_features, by = c("ToNodeID" = "node_id"))

mydata <- as.data.frame(master)
mydata <- mydata %>% mutate(Sign = (Sign+1)/2)

mylogit <- glm(Sign ~ embeddedness + total_in + pos_in + neg_in + total_out + pos_out + neg_out, data = mydata, family = "binomial")

summary(mylogit)
```

The following is a list of all packages used to generate these results. (Leave at very end of file.)

```{r}
sessionInfo()
```